### ISSUE TITLE
Version storage and release trigger

### ISSUE THREAD

**Issue by balbasty** [MPython-Package-Factory/mpython-core#6]
Right now, a release is triggered every time pyproject is changed, right? Even if the version is not changed.

Could we make it so that the release is triggered only if the version is changed?

Maybe we could have:
- a `mpython/_version.py` file that contains only `__version__ = "XX.YY.ZZ"`
- this version imported in `mpython/__init__.py`, e.g. `from ._version import __version__`
- and a dynamic version in the pyproject:
```toml
[project]
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "mpython.__version__"}
```
- trigger the release if a change to `mpython/_version.py` is made: `on: push: mpython/_version.py`

This strategy also allows the version number to be exposed in the python package (`mpython.__version__`).
